[package]
name = "qs3"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2"
rusqlite = { version = "0.40.2", default-features = false, features = ["bundled"] }
tinyjson = "2.5.1"
unicode-general-category = "1.1.0"
unicode-normalization = { version = "0.1.25", default-features = false }

[build-dependencies]
bindgen = "0.72"
