#ifndef QSFI_BUILD_CONSTANTS_H
#define QSFI_BUILD_CONSTANTS_H

#define QSFI_TARGET_SM 121u
#define QSFI_TARGET_COMPUTE_CAPABILITY_MAJOR 12u
#define QSFI_TARGET_COMPUTE_CAPABILITY_MINOR 1u

#define QSFI_ENABLE_FP8 1u
#define QSFI_ENABLE_FP4 1u
#define QSFI_ENABLE_PDL 1u

#define QSFI_GEMM_BACKEND_CUBLASLT 1u
#define QSFI_GEMM_BACKEND_FLASHINFER 2u
#define QSFI_GEMM_BACKEND_CUTLASS 3u

#define QSFI_GEMM_BACKEND QSFI_GEMM_BACKEND_CUBLASLT

#define QSFI_BUILD_TRTLLM_GEN_MOE

#endif
