"""Compile Triton kernels and generate standalone Rust CUDA launchers.

Each source file exposes one @triton.jit entrypoint named kernel.
Tensor parameters are pointers named for that entry's precision fields;
scalar annotations use Triton's type metadata. constexprs come from constants.
The same inspected signature drives compilation and Rust.
"""

import argparse
import hashlib
import importlib.util
import json
import sys
from dataclasses import asdict, dataclass
from os.path import relpath
from pathlib import Path
from typing import Protocol, cast

import qsutil
import triton
import triton.language as tl
from qsutil.config import CudaTarget, DtypeConstant, TritonSpec, parse
from triton.backends.compiler import GPUTarget
from triton.compiler import ASTSource
from triton.runtime.jit import JITFunction

type Scalar = bool | int | float | str | None


@dataclass
class Argument:
    name: str
    triton: str
    rust: str


class KernelMetadata(Protocol):
    name: str
    num_warps: int
    warp_size: int
    shared: int


def dtype(name: str) -> tl.dtype:
    """Translate scalar names into Triton dtypes."""
    return tl.dtype({"f16": "fp16", "f32": "fp32", "f64": "fp64"}.get(name, name))


def scalar_rust_type(ty: tl.dtype) -> str:
    # Half types describe storage bits; generated pointer signatures are unsafe.
    return {
        "bf16": "u16",
        "fp16": "u16",
        "fp32": "f32",
        "fp64": "f64",
        "i8": "i8",
        "i16": "i16",
        "i32": "i32",
        "i64": "i64",
        "u8": "u8",
        "u16": "u16",
        "u32": "u32",
        "u64": "u64",
    }[ty.name]


def rust_type(ty: str) -> str:
    if ty.startswith("*k"):
        return "*const " + scalar_rust_type(dtype(ty[2:]))
    if ty.startswith("*"):
        return "*mut " + scalar_rust_type(dtype(ty[1:]))
    return scalar_rust_type(dtype(ty))


def signature[T](
    kernel: JITFunction[T], spec: TritonSpec
) -> tuple[dict[str, str], dict[str, Scalar | tl.dtype], list[Argument]]:
    types: dict[str, str] = {}
    constants: dict[str, Scalar | tl.dtype] = {}
    arguments: list[Argument] = []
    for param in kernel.params:
        name = param.name
        assert isinstance(name, str)
        if param.is_constexpr:
            value = spec.constants[name]
            constants[name] = (
                dtype(value.dtype) if isinstance(value, DtypeConstant) else value
            )
        else:
            ty = param.annotation_type or "*" + dtype(spec.precision[param.name]).name
            assert isinstance(ty, str)
            types[name] = ty
            arguments.append(Argument(param.name, triton=ty, rust=rust_type(ty)))
    return types, constants, arguments


def rust_source(
    stem: str,
    meta: KernelMetadata,
    grid: list[int],
    arguments: list[Argument],
    constants: dict[str, Scalar | tl.dtype],
) -> str:
    integer_constants = "\n".join(
        f"    pub const {name}: i64 = {value};"
        for name, value in constants.items()
        if isinstance(value, int) and not isinstance(value, bool)
    )
    params = ", ".join(f"mut arg_{a.name}: {a.rust}" for a in arguments)
    pointers = ", ".join(
        f"(&mut arg_{a.name} as *mut {a.rust}).cast::<c_void>()" for a in arguments
    )
    if params:
        params = ", " + params
        pointers += ", "
    return f'''// Generated by build_tools/pysrc/qstriton/builder.py. See {stem}.json for the contract.
use std::ffi::{{c_char, c_void}};
use std::ptr;

#[link(name = "cuda")]
unsafe extern "C" {{
    fn cuModuleLoadData(module: *mut *mut c_void, image: *const c_void) -> i32;
    fn cuModuleGetFunction(function: *mut *mut c_void, module: *mut c_void, name: *const c_char) -> i32;
    fn cuFuncSetAttribute(function: *mut c_void, attribute: i32, value: i32) -> i32;
    fn cuModuleUnload(module: *mut c_void) -> i32;
    fn cuLaunchKernel(function: *mut c_void, gx: u32, gy: u32, gz: u32,
        bx: u32, by: u32, bz: u32, shared: u32, stream: *mut c_void,
        params: *mut *mut c_void, extra: *mut *mut c_void) -> i32;
}}

fn check(code: i32) -> Result<(), i32> {{
    if code == 0 {{ Ok(()) }} else {{ Err(code) }}
}}

pub const GRID: [u32; 3] = {json.dumps(grid)};
pub const BLOCK: [u32; 3] = [{meta.num_warps * meta.warp_size}, 1, 1];
pub const SHARED_BYTES: u32 = {meta.shared};

/// Integer constexprs used to compile this specialization.
pub mod constants {{
{integer_constants}
}}

/// A module owned by the current CUDA context. Neither Send nor Sync.
/// Keep it alive until all queued launches and graphs referencing it are done.
pub struct Kernel {{
    module: *mut c_void,
    function: *mut c_void,
}}

impl Kernel {{
    /// Load and configure before graph capture or timed execution.
    /// # Safety
    /// The caller must keep the current context alive and current through Drop.
    pub unsafe fn load() -> Result<Self, i32> {{
        let mut kernel = Self {{ module: ptr::null_mut(), function: ptr::null_mut() }};
        unsafe {{
            check(cuModuleLoadData(&mut kernel.module, include_bytes!("{stem}.cubin").as_ptr().cast()))?;
            check(cuModuleGetFunction(&mut kernel.function, kernel.module, c"{meta.name}".as_ptr()))?;
            if SHARED_BYTES != 0 {{
                // CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES; set once at load.
                check(cuFuncSetAttribute(kernel.function, 8, SHARED_BYTES as i32))?;
            }}
        }}
        Ok(kernel)
    }}

    /// Enqueue the compiled specialization without allocation or synchronization.
    /// # Safety
    /// Use the loading context and a stream belonging to it. Pointers must have
    /// the element formats, extents and layouts required by the specialization
    /// (see its manifest/source), and remain valid until execution completes.
    /// The caller owns aliasing, ordering and graph/module lifetimes.
    pub unsafe fn launch(&self, stream: *mut c_void{params}) -> Result<(), i32> {{
        // Triton's CUDA ABI includes these even when scratch requirements are zero.
        let mut global_scratch: u64 = 0;
        let mut profile_scratch: u64 = 0;
        let mut args = [{pointers}
            (&mut global_scratch as *mut u64).cast::<c_void>(),
            (&mut profile_scratch as *mut u64).cast::<c_void>()];
        unsafe {{
            check(cuLaunchKernel(self.function, GRID[0], GRID[1], GRID[2],
                BLOCK[0], BLOCK[1], BLOCK[2], SHARED_BYTES, stream,
                args.as_mut_ptr(), ptr::null_mut()))
        }}
    }}
}}

impl Drop for Kernel {{
    fn drop(&mut self) {{
        if !self.module.is_null() {{ unsafe {{ cuModuleUnload(self.module); }} }}
    }}
}}
'''


def build[T](
    prefix: str, kernel: JITFunction[T], spec: TritonSpec, target: CudaTarget
) -> None:
    path = Path(kernel.fn.__code__.co_filename).resolve()
    types, constants, arguments = signature(kernel, spec)
    grid = spec.grid
    if len(grid) != 3 or any(
        type(n) is not int or not 0 < n <= 0xFFFFFFFF for n in grid
    ):
        raise ValueError(f"{prefix}: grid must contain three positive u32 dimensions")
    triton_target = GPUTarget(
        "cuda",
        target.computeCapability.major * 10 + target.computeCapability.minor,
        target.warpSize,
    )
    compiled = triton.compile(
        ASTSource(kernel, types, constants), target=triton_target, options=spec.options
    )
    meta = compiled.metadata
    for field in ("global_scratch_size", "profile_scratch_size"):
        if getattr(meta, field, 0):
            raise ValueError(
                f"{prefix}: {field} is unsupported by the generated launcher"
            )
    if getattr(meta, "num_ctas", 1) != 1:
        raise ValueError(f"{prefix}: CTA clusters require a different launcher")
    cubin = compiled.asm["cubin"]
    # Triton constructs its metadata namedtuple dynamically at compilation time.
    rust = rust_source(
        Path(prefix).name, cast("KernelMetadata", meta), grid, arguments, constants
    )
    manifest = {
        "specialization": prefix,
        "kernel": kernel.__name__,
        "source": str(path),
        "source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "triton_version": triton.__version__,
        "compile_hash": compiled.hash,
        "arguments": [asdict(argument) for argument in arguments],
        "constexprs": constants,
        "grid": grid,
        "metadata": meta._asdict(),
        "cubin_sha256": hashlib.sha256(cubin).hexdigest(),
    }
    output = Path(prefix).parent
    output.mkdir(parents=True, exist_ok=True)
    # No runtime parsing of the manifest or Triton cache; Rust embeds the cubin.
    for suffix, data in {
        ".cubin": cubin,
        ".ptx": compiled.asm["ptx"].encode(),
        ".rs": rust.encode(),
        ".json": (json.dumps(manifest, indent=2, default=str) + "\n").encode(),
    }.items():
        Path(prefix + suffix).write_bytes(data)
    print(
        f"{prefix} ({kernel.__name__}): {len(arguments)} runtime args, grid={grid}, shared={meta.shared}"
    )


def load_kernel(source: Path) -> JITFunction:
    source = source.resolve(strict=True)
    name = "_qstriton_source_" + hashlib.sha256(str(source).encode()).hexdigest()
    module_spec = importlib.util.spec_from_file_location(name, source)
    if module_spec is None or module_spec.loader is None:
        raise ValueError(f"{source}: expected a Python source file")
    module = importlib.util.module_from_spec(module_spec)
    sys.modules[name] = module
    try:
        module_spec.loader.exec_module(module)
        kernel = getattr(module, "kernel", None)
        if not isinstance(kernel, JITFunction):
            raise ValueError(f"{source}: expected @triton.jit entrypoint 'kernel'")  # noqa: TRY004
        return kernel
    finally:
        del sys.modules[name]


def compile_source(
    source: Path, spec: TritonSpec, target: CudaTarget, prefix: str
) -> None:
    build(prefix, load_kernel(source), spec, target)

    dependencies = [relpath(path) for path in source_dependencies(source)]
    for path in [prefix, *dependencies]:
        assert not any(char in path for char in "$# :\\\t\r\n"), path
    Path(prefix + ".d").write_text(prefix + ".rs: " + " ".join(dependencies) + "\n")


def source_dependencies(source: Path) -> list[Path]:
    roots = [Path(__file__).parent, Path(qsutil.__file__).parent]
    files = {p.resolve() for root in roots for p in root.rglob("*.py")}
    files.add(source.resolve())
    return sorted(files)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=str, required=True)
    parser.add_argument("--prefix", type=str, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--target", type=str, required=True)
    args = parser.parse_args()
    spec = parse(args.spec, TritonSpec)
    target = parse(args.target, CudaTarget)
    compile_source(args.source, spec, target, args.prefix)
