# Native constants and AOT dispatch macros for the selected engine.
let
  config = import ../../models/config.nix;
  text = config.model.config;
  gdn = config.kernels.gdn;
  capability = config.target.computeCapability;
  uint = value: "${toString value}u";
  boolean = value: if value then "1u" else "0u";
  float = value: "${builtins.toJSON value}f";
  defines = {
    QSFI_TARGET_SM = uint (capability.major * 10 + capability.minor);
    QSFI_TARGET_COMPUTE_CAPABILITY_MAJOR = uint capability.major;
    QSFI_TARGET_COMPUTE_CAPABILITY_MINOR = uint capability.minor;
    QSFI_ENABLE_FP8 = "1u";
    QSFI_ENABLE_FP4 = "1u";
    QSFI_ENABLE_PDL = boolean config.kernels.attention.pdl;
    QSFI_GEMM_BACKEND_CUBLASLT = "1u";
    QSFI_GEMM_BACKEND_FLASHINFER = "2u";
    QSFI_GEMM_BACKEND_CUTLASS = "3u";
    QSFI_GEMM_BACKEND = "QSFI_GEMM_BACKEND_CUBLASLT";
    QSFI_QWEN36_FULL_ATTENTION_Q_HIDDEN = uint config.dimensions.attention.qWidth;
    QSFI_QWEN36_GDN_NUM_Q_HEADS = uint text.linear_num_key_heads;
    QSFI_QWEN36_GDN_NUM_K_HEADS = uint text.linear_num_key_heads;
    QSFI_QWEN36_GDN_NUM_V_HEADS = uint text.linear_num_value_heads;
    QSFI_QWEN36_GDN_KEY_DIM = uint text.linear_key_head_dim;
    QSFI_QWEN36_GDN_VALUE_DIM = uint text.linear_value_head_dim;
    QSFI_QWEN36_GDN_CONV_WIDTH = uint config.dimensions.gdn.convWidth;
    QSFI_QWEN36_GDN_CONV_HISTORY_LEN = uint config.dimensions.gdn.convHistoryLen;
    QSFI_QWEN36_GDN_THREADS = uint gdn.prepThreads;
    QSFI_QWEN36_GDN_SOFTPLUS_BETA = float gdn.softplusBeta;
    QSFI_QWEN36_GDN_SOFTPLUS_THRESHOLD = float gdn.softplusThreshold;
  };
  dispatch =
    name: runtime: template: type: values:
    builtins.concatStringsSep " \\\n" (
      [
        "#define ${name}(${runtime}, ${template}, ...)"
        "    switch (${runtime}) {"
      ]
      ++ builtins.concatMap (value: [
        "    case ${toString value}: {"
        "        constexpr ${type} ${template} = ${toString value};"
        "        __VA_ARGS__"
        "        break;"
        "    }"
      ]) values
      ++ [
        "    default: {"
        "        std::ostringstream err_msg;"
        ''err_msg << "Unsupported ${runtime}: " << ${runtime};''
        "        FLASHINFER_ERROR(err_msg.str());"
        "    }"
      ]
    )
    + " \\\n}\n";
in
''
  // Generated by build_tools/nixsrc/c.nix from models/config.nix. Do not edit.
  #ifndef QSFI_MACROS_H
  #define QSFI_MACROS_H

''
+ builtins.concatStringsSep "\n" (
  map (name: "#define ${name} ${defines.${name}}") (builtins.attrNames defines)
)
+ "\n\n"
+ builtins.concatStringsSep " \\\n" (
  [ "#define QSFI_NVFP4_TILES(X)" ]
  ++ map (
    tileN:
    assert builtins.isInt tileN;
    "    X(${toString tileN})"
  ) config.kernels.nvfp4.tileN
)
+ "\n"
+ builtins.concatStringsSep " \\\n" (
  [ "#define QSFI_NVFP4_TACTICS(X)" ]
  ++ builtins.concatMap (
    tileN:
    map (
      streamK:
      assert builtins.isBool streamK;
      let
        suffix = if streamK then "STREAM_K" else "DP";
        launcher = "genericFp4GemmKernelLauncher" + (if streamK then "StreamK" else "");
      in
      "    X(QSFI_NVFP4_TILE128X${toString tileN}_${suffix}, ${toString tileN}, ${
            if streamK then "true" else "false"
          }, ${launcher})"
    ) config.kernels.nvfp4.streamK
  ) config.kernels.nvfp4.tileN
)
+ "\n\n"
+
  dispatch "QSFI_DISPATCH_CTA_TILE_Q" "cta_tile_q" "CTA_TILE_Q" "uint32_t"
    config.kernels.attention.ctaTileQ
# Native attention retains both tested Qwen group sizes for its isolated probes.
+ dispatch "QSFI_DISPATCH_GQA_GROUP_SIZE" "group_size" "GROUP_SIZE" "size_t" [
  6
  8
]
+ dispatch "QSFI_DISPATCH_HEAD_DIM" "head_dim" "HEAD_DIM" "size_t" [
  config.dimensions.attention.headDim
]
+ "\n#endif\n"
