# Rust configuration for the selected engine. Keep Rust names/types here and
# model facts, derived dimensions, and implementation choices in config.nix.
let
  config = import ../../models/config.nix;
  text = config.model.config;
  dimensions = config.dimensions;
  recurrentElement =
    {
      bf16 = "u16";
      f32 = "f32";
    }
    .${config.precision.gdn.recurrentState};
  json = builtins.toJSON;
  u32 =
    value:
    assert builtins.isInt value && value >= 0 && value <= 4294967295;
    "u32 = ${toString value}";
  boolean = value: "bool = ${json value}";
  string = value: "&str = ${json value}";
  float = value: "f32 = ${json value}f32";
  strings =
    values:
    "[&str; ${toString (builtins.length values)}] = [${builtins.concatStringsSep ", " (map json values)}]";
  emit =
    indent: fields:
    builtins.concatStringsSep "\n" (
      map (
        name:
        let
          value = fields.${name};
        in
        if builtins.isAttrs value then
          "${indent}pub mod ${name} {\n${emit (indent + "    ") value}\n${indent}}"
        else
          "${indent}pub const ${name}: ${value};"
      ) (builtins.attrNames fields)
    );
in
''
  // Generated by build_tools/nixsrc/rust.nix from models/config.nix. Do not edit.
''
+ emit "" {
  engine = {
    MODEL = string config.engine.model;
    MTP = boolean config.engine.mtp;
  };
  model = {
    HIDDEN_SIZE = u32 text.hidden_size;
    NUM_HIDDEN_LAYERS = u32 text.num_hidden_layers;
    VOCAB_SIZE = u32 text.vocab_size;
    MAX_POSITION_EMBEDDINGS = u32 text.max_position_embeddings;
    RMS_NORM_EPS = float text.rms_norm_eps;
    HIDDEN_ACT = string text.hidden_act;
    TIE_WORD_EMBEDDINGS = boolean text.tie_word_embeddings;
    LAYER_TYPES = strings text.layer_types;
  };
  attention = {
    NUM_Q_HEADS = u32 text.num_attention_heads;
    NUM_KV_HEADS = u32 text.num_key_value_heads;
    HEAD_DIM = u32 dimensions.attention.headDim;
    GROUP_SIZE = u32 dimensions.attention.groupSize;
    Q_WIDTH = u32 dimensions.attention.qWidth;
    KV_WIDTH = u32 dimensions.attention.kvWidth;
    PACKED_Q_GATE_WIDTH = u32 dimensions.attention.packedQGateWidth;
    ROTARY_DIM = u32 dimensions.attention.rotaryDim;
    ROPE_THETA = float text.rope_parameters.rope_theta;
    OUTPUT_GATE = boolean text.attn_output_gate;
    FULL_ATTENTION_INTERVAL = u32 text.full_attention_interval;
  };
  gdn = {
    NUM_KEY_HEADS = u32 text.linear_num_key_heads;
    NUM_VALUE_HEADS = u32 text.linear_num_value_heads;
    KEY_HEAD_DIM = u32 text.linear_key_head_dim;
    VALUE_HEAD_DIM = u32 text.linear_value_head_dim;
    CONV_WIDTH = u32 dimensions.gdn.convWidth;
    CONV_HISTORY_LEN = u32 dimensions.gdn.convHistoryLen;
    PACKED_QKV_CHANNELS = u32 dimensions.gdn.packedQkvChannels;
    OUTPUT_WIDTH = u32 dimensions.gdn.outputWidth;
  };
  mlp = {
    HAS_EXPERTS = boolean (text ? num_experts);
    BF16_KERNEL = string config.kernels.mlp.bf16Kernel;
    NUM_EXPERTS = u32 (text.num_experts or 0);
    NUM_EXPERTS_PER_TOKEN = u32 (text.num_experts_per_tok or 0);
    INTERMEDIATE_SIZE = u32 (text.moe_intermediate_size or text.intermediate_size);
    SHARED_EXPERT_INTERMEDIATE_SIZE = u32 (text.shared_expert_intermediate_size or 0);
  };
  mtp = {
    LAYERS = u32 config.mtp.layers;
    DEDICATED_EMBEDDINGS = boolean config.mtp.dedicatedEmbeddings;
  };
  target = {
    BACKEND = string config.target.backend;
    COMPUTE_CAPABILITY_MAJOR = u32 config.target.computeCapability.major;
    COMPUTE_CAPABILITY_MINOR = u32 config.target.computeCapability.minor;
    WARP_SIZE = u32 config.target.warpSize;
  };
  precision = {
    EMBEDDING = string config.precision.embedding.weight;
    ACTIVATION = string config.precision.projections.activation;
    WEIGHT = string config.precision.projections.weight;
    ACCUMULATION = string config.precision.projections.accumulation;
    PROJECTION_OUTPUT = string config.precision.projections.output;
    RESIDUAL = string config.precision.residual;
    LM_HEAD_OUTPUT = string config.precision.lm_head.output;
    KV_CACHE = string config.precision.kvCache;
    GDN_CONV_STATE = string config.precision.gdn.convState;
    GDN_RECURRENT_STATE = string config.precision.gdn.recurrentState;
    GDN_RECURRENCE_ACCUMULATION = string config.precision.gdn.recurrenceAccumulation;
    GDN_OUTPUT = string config.precision.gdn.output;
  };
}
+ "\n"

+ ''
  // Primitive storage representation; consumers own backend dtype conversion.
  pub type GdnRecurrentElement = ${recurrentElement};
''
