"""Typed Rust owner and argument packing for CuTe's exported MLIR entrypoints."""

from qsutil.config import DtypeConstant

from qscute.signature import Argument


def rust_source(
    symbol: str,
    entrypoint: str,
    arguments: list[Argument],
    constants: dict[str, bool | int | float | str | None | DtypeConstant],
) -> str:
    pointers = [a for a in arguments if a.kind == "pointer"]
    markers = sorted({a.rust.removeprefix("DevicePtr<")[:-1] for a in pointers})
    imports = (
        f"use crate::dtype::{{{', '.join(markers)}}};\nuse crate::ffi::DevicePtr;\n"
        if markers
        else ""
    )
    params = ", ".join(f"arg_{a.name}: {a.rust}" for a in arguments)
    locals = "\n".join(
        f"        let mut arg_{a.name} = arg_{a.name}"
        + (".erase();" if a.kind == "pointer" else ";")
        for a in arguments
    )
    packed_args = "\n".join(
        f"            ptr::from_mut(&mut arg_{a.name}).cast::<c_void>(),"
        for a in arguments
    )
    integer_constants = "\n".join(
        f"    pub const {name}: i64 = {value};"
        for name, value in constants.items()
        if type(value) is int and -(1 << 63) <= value < (1 << 63)
    )
    return f"""// Generated by qscute. See the adjacent JSON manifest for layout/alignment contracts.
{imports}use std::ffi::c_void;
use std::ptr;
use std::sync::atomic::{{AtomicBool, Ordering}};

unsafe extern "C" {{
    #[link_name = "_mlir_{symbol}_cuda_init"]
    fn cuda_init(args: *mut *mut c_void);
    #[link_name = "_mlir_{symbol}_cuda_load_to_device"]
    fn cuda_load_to_device(args: *mut *mut c_void);
    #[link_name = "{entrypoint}"]
    fn entry(args: *mut *mut c_void, count: i32);
}}

#[link(name = "cudart")]
unsafe extern "C" {{
    fn cudaGetDevice(device: *mut i32) -> i32;
    fn cudaLibraryUnload(library: *mut c_void) -> i32;
}}

#[allow(dead_code, non_upper_case_globals)]
pub mod constants {{
{integer_constants}
}}

// CuTe's exported host code stores the kernel handle in a global. A second
// load would overwrite it, so each specialization admits one live owner.
static LOADED: AtomicBool = AtomicBool::new(false);

/// Owns an AOT CUDA library in the current context. Neither Send nor Sync.
/// Retain this owner until launches and graphs using it have completed.
pub struct Kernel {{
    module: *mut c_void,
}}

impl Kernel {{
    /// Load before timing. Include this generated module once per specialization.
    /// # Panics
    /// Panics if this specialization already has a live owner.
    /// # Safety
    /// Keep the loading context alive and current through Drop. Do not call the
    /// object's raw init/load entrypoints outside this owner.
    pub unsafe fn load() -> Result<Self, i32> {{
        assert!(
            LOADED.compare_exchange(false, true, Ordering::Acquire, Ordering::Relaxed).is_ok(),
            "CuTe specialization {symbol} is already loaded",
        );
        let mut module: *mut c_void = ptr::null_mut();
        let mut library = ptr::from_mut(&mut module);
        let mut device = 0_i32;
        let mut status = unsafe {{ cudaGetDevice(&mut device) }};
        if status == 0 {{
            let mut args = [
                ptr::from_mut(&mut library).cast::<c_void>(),
                ptr::from_mut(&mut status).cast::<c_void>(),
            ];
            unsafe {{ cuda_init(args.as_mut_ptr()); }}
            if status == 0 {{
                let mut args = [
                    ptr::from_mut(&mut library).cast::<c_void>(),
                    ptr::from_mut(&mut device).cast::<c_void>(),
                    ptr::from_mut(&mut status).cast::<c_void>(),
                ];
                unsafe {{ cuda_load_to_device(args.as_mut_ptr()); }}
            }}
        }}
        if status != 0 {{
            if !module.is_null() {{
                assert_eq!(unsafe {{ cudaLibraryUnload(module) }}, 0, "CuTe load cleanup failed");
            }}
            LOADED.store(false, Ordering::Release);
            return Err(status);
        }}
        Ok(Self {{ module }})
    }}

    /// Enqueue the AOT host entrypoint on the supplied stream.
    /// # Safety
    /// Bindings must satisfy the compiled shapes, layouts, alignment and scalar
    /// contracts, and remain live through completion. The caller owns aliasing
    /// and stream ordering. Use the loading context; see the kernel source for
    /// launch geometry and any additional preconditions.
    pub unsafe fn launch(&self, {params}) -> Result<(), i32> {{
{locals}
        let mut status = 0_i32;
        let mut args = [
{packed_args}
            ptr::from_mut(&mut status).cast::<c_void>(),
        ];
        unsafe {{ entry(args.as_mut_ptr(), args.len() as i32); }}
        if status == 0 {{ Ok(()) }} else {{ Err(status) }}
    }}
}}

impl Drop for Kernel {{
    fn drop(&mut self) {{
        assert_eq!(unsafe {{ cudaLibraryUnload(self.module) }}, 0, "CuTe unload failed");
        LOADED.store(false, Ordering::Release);
    }}
}}
"""
