"""Compile Triton kernels and generate standalone Rust CUDA launchers.

Each file defines one JITFunction and matches a config.kernels entry by stem.
Unannotated parameters are pointers named for that entry's precision fields;
annotated scalars use Triton's type metadata. constexprs come from constants.
The same inspected signature drives compilation and Rust.
"""

import argparse
import hashlib
import importlib.util
import json
import sys
from importlib.machinery import ModuleSpec, SourceFileLoader
from pathlib import Path

import triton
import triton.language as tl
from triton.backends.compiler import GPUTarget
from triton.compiler import ASTSource
from triton.runtime.jit import JITFunction


def dtype(name):
    """Translate the model config's scalar spelling into a Triton dtype."""
    return tl.dtype({"f16": "fp16", "f32": "fp32", "f64": "fp64"}.get(name, name))


def scalar_rust_type(ty):
    # Half types describe storage bits; generated pointer signatures are unsafe.
    return {
        "bf16": "u16",
        "fp16": "u16",
        "fp32": "f32",
        "fp64": "f64",
        "i8": "i8",
        "i16": "i16",
        "i32": "i32",
        "i64": "i64",
        "u8": "u8",
        "u16": "u16",
        "u32": "u32",
        "u64": "u64",
    }[ty.name]


def rust_type(ty):
    if ty.startswith("*k"):
        return "*const " + scalar_rust_type(dtype(ty[2:]))
    if ty.startswith("*"):
        return "*mut " + scalar_rust_type(dtype(ty[1:]))
    return scalar_rust_type(dtype(ty))


def signature(kernel, settings):
    types, constants, arguments = {}, {}, []
    for param in kernel.params:
        if param.is_constexpr:
            value = settings["constants"][param.name]
            constants[param.name] = (
                dtype(value["dtype"]) if isinstance(value, dict) else value
            )
        else:
            ty = (
                param.annotation_type
                or "*" + dtype(settings["precision"][param.name]).name
            )
            types[param.name] = ty
            arguments.append({"name": param.name, "triton": ty, "rust": rust_type(ty)})
    return types, constants, arguments


def rust_source(stem, meta, grid, arguments):
    params = ", ".join(f"mut arg_{a['name']}: {a['rust']}" for a in arguments)
    pointers = ", ".join(
        f"(&mut arg_{a['name']} as *mut {a['rust']}).cast::<c_void>()"
        for a in arguments
    )
    if params:
        params = ", " + params
        pointers += ", "
    return f'''// Generated by build_tools/qs3_triton/builder.py. See {stem}.json for the contract.
use std::ffi::{{c_char, c_void}};
use std::ptr;

#[link(name = "cuda")]
unsafe extern "C" {{
    fn cuModuleLoadData(module: *mut *mut c_void, image: *const c_void) -> i32;
    fn cuModuleGetFunction(function: *mut *mut c_void, module: *mut c_void, name: *const c_char) -> i32;
    fn cuFuncSetAttribute(function: *mut c_void, attribute: i32, value: i32) -> i32;
    fn cuModuleUnload(module: *mut c_void) -> i32;
    fn cuLaunchKernel(function: *mut c_void, gx: u32, gy: u32, gz: u32,
        bx: u32, by: u32, bz: u32, shared: u32, stream: *mut c_void,
        params: *mut *mut c_void, extra: *mut *mut c_void) -> i32;
}}

fn check(code: i32) -> Result<(), i32> {{
    if code == 0 {{ Ok(()) }} else {{ Err(code) }}
}}

pub const GRID: [u32; 3] = {json.dumps(grid)};
pub const BLOCK: [u32; 3] = [{meta.num_warps * meta.warp_size}, 1, 1];
pub const SHARED_BYTES: u32 = {meta.shared};

/// A module owned by the current CUDA context. Neither Send nor Sync.
/// Keep it alive until all queued launches and graphs referencing it are done.
pub struct Kernel {{
    module: *mut c_void,
    function: *mut c_void,
}}

impl Kernel {{
    /// Load and configure before graph capture or timed execution.
    /// # Safety
    /// The caller must keep the current context alive and current through Drop.
    pub unsafe fn load() -> Result<Self, i32> {{
        let mut kernel = Self {{ module: ptr::null_mut(), function: ptr::null_mut() }};
        unsafe {{
            check(cuModuleLoadData(&mut kernel.module, include_bytes!("{stem}.cubin").as_ptr().cast()))?;
            check(cuModuleGetFunction(&mut kernel.function, kernel.module, c"{meta.name}".as_ptr()))?;
            if SHARED_BYTES != 0 {{
                // CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES; set once at load.
                check(cuFuncSetAttribute(kernel.function, 8, SHARED_BYTES as i32))?;
            }}
        }}
        Ok(kernel)
    }}

    /// Enqueue the compiled specialization without allocation or synchronization.
    /// # Safety
    /// Use the loading context and a stream belonging to it. Pointers must have
    /// the element formats, extents and layouts required by the specialization
    /// (see its manifest/source), and remain valid until execution completes.
    /// The caller owns aliasing, ordering and graph/module lifetimes.
    pub unsafe fn launch(&self, stream: *mut c_void{params}) -> Result<(), i32> {{
        // Triton's CUDA ABI includes these even when scratch requirements are zero.
        let mut global_scratch: u64 = 0;
        let mut profile_scratch: u64 = 0;
        let mut args = [{pointers}
            (&mut global_scratch as *mut u64).cast::<c_void>(),
            (&mut profile_scratch as *mut u64).cast::<c_void>()];
        unsafe {{
            check(cuLaunchKernel(self.function, GRID[0], GRID[1], GRID[2],
                BLOCK[0], BLOCK[1], BLOCK[2], SHARED_BYTES, stream,
                args.as_mut_ptr(), ptr::null_mut()))
        }}
    }}
}}

impl Drop for Kernel {{
    fn drop(&mut self) {{
        if !self.module.is_null() {{ unsafe {{ cuModuleUnload(self.module); }} }}
    }}
}}
'''


def build(path, config, output):
    stem = path.stem
    loader = SourceFileLoader(f"qs3_kernel_{stem}", str(path))
    spec = ModuleSpec(loader.name, loader, origin=str(path))
    spec.has_location = True
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    loader.exec_module(module)
    (kernel,) = (
        value
        for value in vars(module).values()
        if isinstance(value, JITFunction) and value.module == spec.name
    )
    settings = config["kernels"][stem]
    types, constants, arguments = signature(kernel, settings)
    grid = settings["grid"]
    device = config["target"]
    cc = device["computeCapability"]
    target = GPUTarget("cuda", cc["major"] * 10 + cc["minor"], device["warpSize"])
    compiled = triton.compile(
        ASTSource(kernel, types, constants), target=target, options=settings["options"]
    )
    meta = compiled.metadata
    cubin = compiled.asm["cubin"]
    rust = rust_source(stem, meta, grid, arguments)
    manifest = {
        "source": str(path),
        "source_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "triton_version": triton.__version__,
        "compile_hash": compiled.hash,
        "arguments": arguments,
        "constexprs": constants,
        "grid": grid,
        "metadata": meta._asdict(),
        "cubin_sha256": hashlib.sha256(cubin).hexdigest(),
    }
    output.mkdir(parents=True, exist_ok=True)
    # No runtime parsing of the manifest or Triton cache; Rust embeds the cubin.
    for suffix, data in {
        ".cubin": cubin,
        ".ptx": compiled.asm["ptx"].encode(),
        ".rs": rust.encode(),
        ".json": (json.dumps(manifest, indent=2, default=str) + "\n").encode(),
    }.items():
        (output / (stem + suffix)).write_bytes(data)
    print(f"{path}: {len(arguments)} runtime args, grid={grid}, shared={meta.shared}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True, help="evaluated Nix JSON")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("kernels", type=Path, nargs="+")
    args = parser.parse_args()
    if len({p.stem for p in args.kernels}) != len(args.kernels):
        parser.error("kernel filenames must have unique stems")
    config = json.loads(args.config.read_text())
    for path in args.kernels:
        build(path, config, args.out)
